arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/flutter_gen/gen_l10n

output-class: AppLocalizations
untranslated-messages-file: untranslated_messages_report.json

