arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/l10n
untranslated-messages-file: untranslated_messages.json
suppress-warnings: true
supported-locales:
  - en
  - ha
  - ig
  - pcm
  - yo
